# Generated by Django 4.2.7 on 2023-11-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_quest_can_pause_room_guest_can_pause'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_pause',
            new_name='quest_can_pause',
        ),
    ]
